### ISSUE TITLE
Fails on imports that are part of a string

### ISSUE THREAD

**Issue by Rheeseyb** [benawad/destiny#111]
Our project is somewhat unique in that it has to handle evaluating arbitrary code, so our tests include stringified code examples, some of which include import statements. Since this project uses a regex to capture all import statements it is being tripped up by e.g.:
```
const sampleUserCode = `import { MyButton } from "./mybutton"`
```

In our project we use Typescript to parse and tokenise a source file, and then traverse the nodes to find all of the import statements. In a very simplified nutshell it looks something like this:
```
import * as TS from 'typescript'
const sourceFile = TS.createSourceFile(filename, sourceText, TS.ScriptTarget.ES3)
const topLevelNodes = sourceFile.getChildren(sourceFile)
const imports = topLevelNodes.filter(TS.isVariableStatement)
```

It's unlikely to be a simple change but would certainly make this project more robust (I saw there was previously this similar issue #42). We used https://ts-ast-viewer.com/ extensively to help us understand that AST generated by Typescript (it's open source too: https://github.com/dsherret/ts-ast-viewer). Alternative to that there is also acorn (https://github.com/acornjs/acorn) for doing a similar thing with js code.

**Comment by AnatoleLucet** [comment]
@Rheeseyb Thank you for your proposal with Typescript AST, but we've decided to stick with the regex for performance reasons. See #127.

Destiny shouldn't try to resolve imports that are parts of a string from now.
![great success](https://user-images.githubusercontent.com/35486736/80547292-22db3300-89b8-11ea-850a-ccedf1d06aff.png)

**Comment by Rheeseyb** [comment]
Oh wow, that was indeed a huge performance difference! Thanks
