### ISSUE TITLE
Appears to crawl up to dangerous parent directories.

### ISSUE THREAD

**Issue by amadeus** [benawad/destiny#12]
No worries, no harm was done, but I ran into this error and didn't think it was worth trying to fix to get the script continuing:

```
ENOENT: no such file or directory, scandir '/Users/utils'
```

I was operating the tool from `/Users/amadeus/Development/git_repo/subfolder`

Could probably use something to prevent it from trying to crawl up and outside of the existing execution directory.

**Comment by benawad** [comment]
Is it possible to share the repo?

It should only crawl the path you specify, but maybe an import is messing it up and I definitely don't want it crawling around someones personal files.

**Comment by amadeus** [comment]
Unfortunately no, I was running it on the discord repo for funzies, heh.

**Comment by benawad** [comment]
No worries, I have a couple ideas on how to reproduce it.

**Comment by AnatoleLucet** [comment]
Is this still an issue?

**Comment by benawad** [comment]
worth testing again, the internals have changed and I don't think it should crawl up anymore

@amadeus would you mind running it again (ps it's been renamed to `destiny`)

**Comment by sQVe** [comment]
Closing due to lack of feedback.

@amadeus If your still having problems just ping and I'll reopen the issue.
