### ISSUE TITLE
double check tilde works 

### ISSUE THREAD

**Issue by benawad** [benawad/destiny#125]
`destiny ~/**/*.js`

**Comment by AnatoleLucet** [comment]
Do you mean that the tilde isn't recognized?

**Comment by benawad** [comment]
yeah was testing on someone else's computer and didn't work, this was a reminder to check what happens when I include a ~

**Comment by AnatoleLucet** [comment]
`path.resolve` doesn't resolve `~` to the home dir. A simple condition that checks for `~/` at the beginning of the path or `~` and replace it by `os.homedir()` should do the trick.

**Comment by AnatoleLucet** [comment]
Should be resolved with 40b36a2
