### ISSUE TITLE
destiny does not crawl `require` statements correctly

### ISSUE THREAD

**Issue by lifeiscontent** [benawad/destiny#126]
I ran destiny on my node_modules folder and had `ejs` npm package installed.

even though the code is correctly pointing to the right path, destiny seems to think its not.

Steps to reproduce:

1. create new folder
2. yarn add ejs
3. run destiny on node_modules folder `destiny "node_modules/**/*.*"`

log:

```
ERROR: Cannot find import ./utils for /Users/someone/Source/demo/node_modules/ejs/ejs.js
```

**Comment by AnatoleLucet** [comment]
Just a curiosity question, why in the hell would you run Destiny on your `node_modules`? :smile:

Joke aside, I'll try to run Destiny on ejs' repo and see if I can find an error that we're not aware yet.

**Comment by AnatoleLucet** [comment]
Well I don't really understand what's the issue you're pointing at. `node_modules/ejs/ejs.js` try to import `./utils.js` which doesn't exist.

There's the same `ejs.js` in `node_modules/ejs/lib` and a `utils.js` beside it.
If I run Destiny on `lib`, it prints out the following (which is the correct expected output):
```
lib
├──ejs
│  └──utils.js
└──ejs.js
```

**Comment by AnatoleLucet** [comment]
I'm closing this for now since it seems more like you're not correctly using Destiny then a bug.
You can check our [documentation](https://github.com/benawad/destiny/wiki) if you want.

**Comment by lifeiscontent** [comment]
@AnatoleLucet I did it more or less as a demonstration, its not a practical use case, but more or less a way to find bugs. Regardless of this being in node_modules or not, it should still not error.

**Comment by AnatoleLucet** [comment]
> Regardless of this being in node_modules or not, it should still not error.

Why? Maybe it's just me, but it actually seems to works correctly.

There's the following in the `package.json`:
```json
"main": "./lib/ejs.js",
```
So the `./lib/ejs.js` is the correct file (see [npm's doc](https://docs.npmjs.com/files/package.json#main)). I don't know why there's an `ejs.js` file in `node_modules/ejs`, but it's clearly not a file that's intended to be used.
