### ISSUE TITLE
Does not work with React

### ISSUE THREAD

**Issue by darkalghul** [benawad/destiny#131]
When running `npx destiny src` I got the following output.

![Screen Shot 2020-04-28 at 14 50 18](https://user-images.githubusercontent.com/9381648/80536425-9d2b9900-895f-11ea-8ba4-c5bd1a614300.png)

But my folder structure it looks the same as before, nothing change.

React is not supported?

**Comment by AnatoleLucet** [comment]
You need to use the `--write` (or `-w`) flag.
```
npx destiny src --write
```
https://github.com/benawad/destiny/wiki#write
