### ISSUE TITLE
ignore `node_modules` directories

### ISSUE THREAD

**Issue by lifeiscontent** [benawad/destiny#138]
It would be nice to run destiny in projects that don't use a `src` folder. Currently not possible due to `node_modules` being in the same dir.

**Comment by ChrisBrownie55** [comment]
I like the idea of adding a `-I` (or `-i`) and `--ignore` option. I think we'd just need to run all of the files that matched the original glob through this glob. If they match the `--ignore` glob we'd just remove them from the output. There could be a more efficient way to do this though (I mean `node_modules` should just be ignored by default IMO)
