### ISSUE TITLE
Changes imports to use incompatible \\ (double backslashes) on Windows

### ISSUE THREAD

**Issue by ChrisBrownie55** [benawad/destiny#141]
When running destiny on Windows from powershell, it changes all of the imports to use double backslashes so:

```js
import './App'
```

became

```js
import '.\\App'
```

And this completely doesn't work when running my code with `vite serve src` as I believe it's using ES Module import syntax in the browser to resolve files

**Comment by ChrisBrownie55** [comment]
Is there a way to disable these backslashes? If so, is there a way we could add it to the README and the `--help` info?

**Comment by AnatoleLucet** [comment]
Yes, we're aware of that from #135.
A fix is going to be reviewed #140.
