### ISSUE TITLE
Incompatible with TypeScript projects

### ISSUE THREAD

**Issue by ChrisBrownie55** [benawad/destiny#145]
TypeScript does not support imports like `import x from './index/xyz'` (you're trying to import `./index/xyz.tsx` here) when there is also a directory called `index/xyz/` because it compiles the code to `import x from './index/xyz/index.js`. Normally I'd just include the file extension `.tsx` but TypeScript hates that.

Example of a project that would break TypeScript with `'./index/App'` import:
```tree
src/
├── index
│   ├── App
│   │   ├── App.css
│   ├── App.tsx
│   ├── index.css
└── index.tsx
```

That part is a purely TypeScript problem that I don't know why they thought of that as a feature but I found a workaround after asking around. Replace `.tsx` with `.js` when writing the import and it works flawlessly.

```tsx
import App from './index/App.js'; // but we're really importing ./index/App.tsx
```

This was fine until I ran Destiny again. Destiny doesn't have a way to resolve the `.js` extension to the `.tsx` extension (understandably so, I blame TypeScript in this mess) therefore I'm unable to use TypeScript alongside Destiny, it seems to be one or the other (or constantly change file extensions in imports to satisfy one then the other).

**Comment by AnatoleLucet** [comment]
If I fully understand, when you're importing `import x from './index/xyz'` typescript's compiler is transpiling this into `import x from './index/xyz/index.js'` but it's supposed to be `import x from './index/xyz.js'`?

**Comment by ChrisBrownie55** [comment]
Yeah, that's exactly the problem I'm encountering 👍

**Comment by AnatoleLucet** [comment]
> I found a workaround after asking around

Did you opened an issue on [Microsoft/TypeScript](https://github.com/Microsoft/TypeScript)?
Maybe it's supposed to do what it does?

Also can you share a repo and steps to reproduce the issue please? 🙏

**Comment by ChrisBrownie55** [comment]
I didn't open an issue yet, seems like something that TypeScript isn't going to want to change but I can open one up and see what happens. And I'll see what I can do about making a repro for this

**Comment by ChrisBrownie55** [comment]
So I was looking into it more while trying to create a replication and it looks like the issue might have to deal with specifically the configuration that the React TypeScript Snowpack starter `@snowpack/app-template-react-typescript` is using as I can't replicate this issue at all with just plain old TypeScript.

**Comment by ChrisBrownie55** [comment]
I'm gonna close this for now as it seems that this is a Snowpack specific problem
