### ISSUE TITLE
remote.require()

### ISSUE THREAD

**Issue by Robertfj** [benawad/destiny#147]
I'm using Electron with React.

Whenever i have a remote.require(), the filepath will never get resolved, as it's really resoving it from top level main.js, and Destiny is trying to resolve it from where it's called.

would it be possible to add an exclution in the regular expression for 'remote.require' ?

Sample import:
```
const sshService = remote.require("./src/services/sshService.js");
```

**Comment by AnatoleLucet** [comment]
By now there's no way to do this with Destiny.
But some work is in progress to resolve "non-vanilla" imports (see #123). I'll add this case to #123 to keep everything in the same place and close this issue.
Thank you for pointing this out.
