### ISSUE TITLE
Why use this project over webpack?

### ISSUE THREAD

**Issue by DGKSK8LIFE** [benawad/destiny#152]

**Comment by benawad** [comment]
because webpack doesn't prettify folder structures as far as I'm aware

**Comment by DGKSK8LIFE** [comment]
@benawad Yes it does: https://github.com/hawkins/prettier-webpack-plugin and https://github.com/danielterwiel/prettier-eslint-webpack-plugin

**Comment by AnatoleLucet** [comment]
@DGKSK8LIFE I think you misunderstood the goal of Destiny.

Destiny prettify your **folder structure** and not the code inside you files.

**Comment by DGKSK8LIFE** [comment]
k @AnatoleLucet

**Comment by AnatoleLucet** [comment]
you're welcome
