### ISSUE TITLE
Restructure subfolders

### ISSUE THREAD

**Issue by AnatoleLucet** [benawad/destiny#20]
In [this example](https://github.com/shivekkhurana/appuity-frontend/tree/develop/src) of fractal structure from [this article](https://hackernoon.com/fractal-a-react-app-structure-for-infinite-scale-4dab943092af), they are showing how they use the fractal structure only in sub folders of `src/`.
So `src/` isn't structured in a fractal way but sub folders like `components`, `pages`, `modules`... are.

I only see one way of doing this with the current version of Destiny. Executing Destiny in each sub folders (`destiny src/components`, `destiny src/pages`...). For sure that's not great.

### CLI idea:

```bash
destiny src --sub=components --sub=pages # ...
# or 
destiny src/components src/pages # ...
# or
destiny src/* --ingore src/utils
```
`--ignore` flag: #8, #11, #17

### Config file idea:

```js
paths: [
  'src/component',
  'src/pages',
  // ...
]

// or a more "tsc like" way
rootDir: './src',
paths: [
  'component',
  'pages',
  // ...
]
```

**Comment by benawad** [comment]
I like it and by default we can assume the first level is the root.

**Comment by sQVe** [comment]
This is now supported via https://github.com/benawad/destiny/pull/55. As @benawad mention we should remove the `detectRoots` option and just keep it simple. If a user wants to only restructure subfolders they should input those subfolders.

A fast way to do this would be `npx destiny src/*/`.

Closing.
