### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by sQVe** [benawad/destiny#25]
Hey :wave:,

Do you have any thoughts on a CI system for this repo? I think it would be great to have some automated tests for PRs etc.

I would recommend **Travis** and I would be happy to set it up if needed.

**Comment by benawad** [comment]
I want to set something up like that, but haven't gotten to it yet.

I was thinking of trying GitHub Actions, but if you like Travis better I'm good with that too if you want to set it up.

**Comment by AnatoleLucet** [comment]
What about GitHub Actions?

**Comment by sQVe** [comment]
@benawad It would be fun to try GitHub Actions. I always default to **Travis** because that is what I've been using for years.

**Comment by sQVe** [comment]
@benawad Just so you know I'm unable to help out with this as I'm not a maintainer. So your not waiting for me to set it up or something.

**Comment by benawad** [comment]
@sQVe @AnatoleLucet just invited both of you as collaborators
