### ISSUE TITLE
Adding Configuration Options is Next

### ISSUE THREAD

**Issue by benawad** [benawad/destiny#28]
I'm pretty happy with the engine now and should make it easier to layer configuration options on it.

Biggest change I made is `buildGraph` now takes an array of files instead of a folder. Will make it easier to ignore files and process files by root.

**Comment by AnatoleLucet** [comment]
Two questions:
1. Should the options given through the CLI take over the config file? For me it's a yes.
2. Should the options of type array be combined or fully replaced? For example the paths given through the CLI take over the paths in the config file. For me they should be combined but it can probably depends.

**Comment by sQVe** [comment]
@AnatoleLucet I think options given via the **cli** should override any other option. I think it would be confusing to combine.

**Comment by benawad** [comment]
I agree, combining will get messy

**Comment by sQVe** [comment]
Maybe we should close this unless we want to discuss specific options?

The ability to configure `destiny` via the cli and config is now possible.
