### ISSUE TITLE
Error when importing files with same name from different folders

### ISSUE THREAD

**Issue by sokki** [benawad/destiny#33]
For

```
| index.js
| - dir1/file.js
| - dir2/file.js
```

I get a `UnhandledPromiseRejectionWarning: Error: fatal: destination exists` because the fractal tree resolves this to
```
{
    "index.js": "index.js",
    "dir1/file.js": "index/file.js",
    "dir2/file.js": "index/file.js",
}
```

Two options to approach this:
1. Keep sub-directories (`"dir1/file.js": "index/dir1/file.js",`)
2. Rename the file (e.g. (`"dir1/file.js": "index/dir1-file.js",`)

I think both approaches might get quite messy when dealing with deeper nested structures tho 🤔 
But I'd favor option 2 since it makes it easier to manually rename to something more useful.

**Comment by AnatoleLucet** [comment]
I also think the second option is better. The first one wouldn't respect the "fractal structure rules".

**Comment by AnatoleLucet** [comment]
What about asking the user if he want to rename the file, and if yes, asking him to enter a new name?

**Comment by sQVe** [comment]
@AnatoleLucet I think we should try to be as opinionated as possible, like prettier, and also aim to be zero-conf.

Asking the user for input is problematic when `destiny` runs on CI or any other automated way. We could introduce a optional option where the user has power to edit conflicts, just like a git merge conflict. That might be a bit overkill currently though.

**Comment by AnatoleLucet** [comment]
Yes you're right, that's a better idea 👍

**Comment by sQVe** [comment]
This should now be fixed once https://github.com/benawad/destiny/pull/34 is released. Closing.
