### ISSUE TITLE
Why double index?

### ISSUE THREAD

**Issue by zaguiini** [benawad/destiny#41]
![image](https://user-images.githubusercontent.com/26530524/74694492-188a0500-51cf-11ea-8491-42793e4bc23a.png)

In this image on the docs I see both `index.js`  and `index/` folder.

Why use this approach? Isn't it bad for the compiler/ambiguous to have both?

Why don't simply put  `index/` folder's contents outside of it? It would look clear and it wouldn't break encapsulation.

I'm not bashing it, to be clear, I'm just curious about why this solution?

**Comment by sQVe** [comment]
`destiny` is in early development stage. The resulting structure that `destiny` currently outputs is a reflection of some generalization and simplification. I think the next goal is to only *run* `destiny` on subfolders of `src`. Do you agree @benawad?

It's worth noting that the current structure has no implications on a compiler. From a compiler or file system stand point there is a big difference between `index.js` and `index/`.

**Comment by AnatoleLucet** [comment]
The following article may help you:
https://hackernoon.com/fractal-a-react-app-structure-for-infinite-scale-4dab943092af

**Comment by benawad** [comment]
@sQVe exactly, you'll define some root folders and then `destiny` will make each one a fractal

**Comment by sQVe** [comment]
Closing this issue as I, hopefully, you've gotten the information you were asking for.

**Comment by moQuez** [comment]
> @sQVe exactly, you'll define some root folders and then `destiny` will make each one a fractal

Awesome! I was just reading that Fractal pattern article and hoped to have the chance to define multiple root entry points.  Is there anyone working on this? I might want to help out on that!

**Comment by AnatoleLucet** [comment]
@moQuez Do you mean multiples paths / entry points?
```
destiny src/pages src/components
```

**Comment by moQuez** [comment]
> @moQuez Do you mean multiples paths / entry points?
> 
> ```
> destiny src/pages src/components
> ```

Yes, I just noticed a comment on that on another issue. Probably this is something that would be better placed on a section of the docs were talking about Fractal pattern and multiple root/entry points.

**Comment by AnatoleLucet** [comment]
@moQuez I'm currently working on the doc. I don't have a lot of free time to work on it but it should be out this week-end.
It's going to cover the concept of our fractal files structure bases on Pythagore's Tree, the config file options, the cli flags, and some examples...

**Comment by AnatoleLucet** [comment]
And btw, you can also give your paths to destiny in the config file via the `include` property (array of strings)
#83
