### ISSUE TITLE
Errors for commented out imports and exports

### ISSUE THREAD

**Issue by alubbe** [benawad/destiny#42]
The tool does not recognize when an invalid import statement has been commented out, like this:
```js
// export { nonsense } from './invalid/path';
```
It throws this error until we delete the line:
```
UnhandledPromiseRejectionWarning: Error: Cannot find module './invalid/path' from 'some/folder'
```
It would be great if it would ignore these lines - does the currently logic depend on pattern matching or does it parse the AST of the files?

**Comment by sQVe** [comment]
@alubbe Nice find!

The current logic utilizes pattern matching to find imports and exports. It should of course ignore commented out lines.

**Comment by alubbe** [comment]
Okay so then ignoring lines with a preceding `//` is simple, but I'm not sure what the most economic/effient way would be to find out whether you're in a (possible nested) `/* ... */` block - how would you resolve that with pattern matching?

**Comment by alubbe** [comment]
Ok so JavaScript does not have nested comments, so it suffices to find the last `*/` and then scan if there are any `/*` between that and your current position

**Comment by alubbe** [comment]
or, more economically, find the nearest preceding `/*` and the see if it has been closed by a `*/` before your current position - but you probably want to keep track of all of this per file because otherwise you're doing this per line with an import statement

**Comment by alubbe** [comment]
anyways, thanks for this tool - I hope to try it again once it ignores comments (atm our code base is just too large and littered with comments for me to clean up by hand)

**Comment by sQVe** [comment]
@alubbe There are plenty of ways to solve this problem. I'll ping you once it is done. Cheers for the input. :+1:

**Comment by sQVe** [comment]
@alubbe This should now be fixed on the next release of `destiny`.

**Comment by alubbe** [comment]
amazing, thanks!

**Comment by sQVe** [comment]
@alubbe This is now released.
