### ISSUE TITLE
I added a GitHub Action for Deploying to NPM

### ISSUE THREAD

**Issue by benawad** [benawad/destiny#46]
@sQVe @AnatoleLucet 

I just grabbed an existing NPM publish action, so feel free to swap it out if you want something different, but you can now deploy the package to NPM.

Now, when someone changes the version in `package.json` to `1.2.3` and pushes a commit with the message `Release 1.2.3`, the GitHub action will create a new tag `v1.2.3` and publish the package to the NPM registry.

**Comment by benawad** [comment]
Might be worth adding `semantic-release` and auto generating change logs

**Comment by sQVe** [comment]
@benawad That's awesome! It would be nice, if possible, to release on GitHub too.

In the future it might be worth considering https://github.com/semantic-release/semantic-release which is really nice with https://www.conventionalcommits.org. That would automate releases to npm and GitHub and also create changelogs etc.

**Comment by sQVe** [comment]
@benawad I usually run the following config https://github.com/sQVe/colorally/blob/develop/.releaserc.json. 

I'd love to help out but it's pretty hard when not having access to the tokens etc! 👍

**Comment by AnatoleLucet** [comment]
That's really nice, it's going to be useful! Anyway, I'm not going to be really active on the project for the next week. It's pretty hard to write code with a clavicle in half... 😑

**Comment by sQVe** [comment]
Also, we should probably have a master and develop branch. The develop branch should be set to default @ GitHub. Master branch points to latest release.

**Comment by AnatoleLucet** [comment]
And keeping important releases on branches.

**Comment by sQVe** [comment]
@benawad The npm-publish action is failing every time is doesn't match. We should probably make if fail gracefully or start using a `develop` branch.

**Comment by benawad** [comment]
I made `develop` the default branch and added credentials for `semantic-release`. I tried setting up the CI for it too, but it says no relevant changes found (https://github.com/benawad/destiny/runs/454438634?check_suite_focus=true) each time so I think there's a needs to be a tweak of some sort.

**Comment by sQVe** [comment]
This now works. I also added `@semantic-release/changelog`, `@semantic-release/git` which updates our https://github.com/benawad/destiny/blob/develop/CHANGELOG.md automatically and also fixes tags etc on GitHub.

Closing.

**Comment by sQVe** [comment]
@benawad Could you please set the `master` branch to protected? We don't want to be able to force push to that branch.
