### ISSUE TITLE
Preview tree

### ISSUE THREAD

**Issue by sQVe** [benawad/destiny#47]
I think the default behavior of `destiny` should be to output a preview of the fractal tree. This goes in line with how `prettier` handles things as it only writes when given the `--write` option.

What do you guys think @benawad @AnatoleLucet @sokki? I'm currently writing a `treePrinter` module but the core application also needs to be restructured a bit to handle this nicely.

**Comment by benawad** [comment]
I like this

**Comment by AnatoleLucet** [comment]
Also like it!

**Comment by sQVe** [comment]
Here's an example of the desired output:
```bash
src
├── index
│  ├── formatFileStructure
│  │  ├── buildGraph
│  │  │  └── addEdge.ts
│  │  ├── buildGraph.ts
│  │  ├── findEntryPoints.ts
│  │  ├── fixImports
│  │  │  └── makeImportPath.ts
│  │  ├── fixImports.ts
│  │  ├── moveFiles.ts
│  │  ├── removeEmptyFolders.ts
│  │  ├── shared
│  │  │  ├── customResolve.ts
│  │  │  ├── findEdges.ts
│  │  │  ├── findSharedParent.ts
│  │  │  ├── Graph.ts
│  │  │  └── isTestFile.ts
│  │  ├── toFractalTree
│  │  │  └── hasCycle.ts
│  │  └── toFractalTree.ts
│  ├── formatFileStructure.ts
│  ├── getFilePaths.ts
│  ├── shared
│  │  └── RootOption.ts
│  └── treePrinter.ts
├── index.ts
└── shared
   └── logger.ts
```
I'm currently working on the data handling to do this. I have all the leafs listed and sorted already. Now I need to build the tree and then visualize it.

**Comment by AnatoleLucet** [comment]
Maybe you've already planned to do this, but it could be nice to have different color for folders like `tree` is doing:
![](https://i.gyazo.com/698b705a2beb93b19dbd4fc64728c174.png)
It's easier to read.

And also sorting the list by dirs first?

**Comment by sQVe** [comment]
@AnatoleLucet Yeah, I'm planning to colorize the output somewhat for readability. The sorting of all individual leafs, where directories weight heavier, is already implemented. Currently working on building the actual branches in a easy to understand and flexible structure.

**Comment by AnatoleLucet** [comment]
#69 🎉
