### ISSUE TITLE
Handle `.spec.js` and `__mocks__` different

### ISSUE THREAD

**Issue by sokki** [benawad/destiny#5]
This tool is a great idea Ben! 
It would be awesome if this would end the endless debates about folder structures like prettier ended the debates about formatting.

I ran it against a small project and quickly realised, that it doesn't play well when u have `.spec.` files and `__mock__` folders inside your src folder.

So this
![image](https://user-images.githubusercontent.com/665748/74558696-09068400-4f63-11ea-97eb-d23e58af6985.png)

becomes:
![image](https://user-images.githubusercontent.com/665748/74558721-16237300-4f63-11ea-9557-9929de77c11f.png)

instead of:
![image](https://user-images.githubusercontent.com/665748/74558840-571b8780-4f63-11ea-94fd-91c9d355e183.png)

**Comment by benawad** [comment]
How do the files import each other?

Would you mine adding this as a test case?

**Comment by benawad** [comment]
should be fixed now
