### ISSUE TITLE
Duplicate unused files

### ISSUE THREAD

**Issue by waynevanson** [benawad/destiny#51]
For some reason, it displayed an unused file twice.

Also, I'd like to see a tree view of the unused files so there's less ambiguity of files/more visual. AT least for the CLI portion of this.

```shell
src/
|-- /index.html
```

```shell
$ /home/wayne/Documents/apollo-orm-test/node_modules/.bin/destiny src
INFO: Resolving files.
INFO: Generating a graph and fractal tree.
INFO: Fixing imports.
INFO: Moving files.
WARN: Unused files:
        index.html
        index.html
INFO: Successfully restructured!
Done in 0.16s.
```

**Comment by sQVe** [comment]
The tree view will be possible once we have https://github.com/benawad/destiny/issues/47. The other issue should be easily fixed.
