### ISSUE TITLE
config file and flags

### ISSUE THREAD

**Issue by AnatoleLucet** [benawad/destiny#8]
As mentioned in #3, it could be nice to have some options. Either with some flags in the cli or a config file.

Here's some of my obvious ideas when we speak about options for a cli:
- Ignored pattern & files/folders names. For example: `butler-cli src --ignore *.js` ingore js files
- Some kind of regex (like ESLint is doing) for the first argument which is the path. For example `butler-cli src/**/*.{ts, tsx}` would only apply changes to `.ts` & `.tsx` files.

Any thought?

**Comment by nmay231** [comment]
Another config option that would be useful is the file path separator, whether it is forwards slash "`/`", back slash "`\`", or inferred (default).

Also, having the ability to leave a comment at the top of the file `/* butler-ignore */` would be helpful in some cases. But that opens a whole other can of worms :wink:

**Comment by benawad** [comment]
I'm thinking of using https://github.com/davidtheclark/cosmiconfig for getting the config file

and https://github.com/tj/commander.js/ to handle flags

**Comment by sQVe** [comment]
Closing issue. Fixed in above references.
