### ISSUE TITLE
Doesnt work on windows

### ISSUE THREAD

**Issue by jesperordrup** [benawad/destiny#81]
Running npx destiny "src/**/*.*" or just npx destiny src prints out a tree that looks like a nice end result - but files and folders are untouched.

**Comment by jesperordrup** [comment]
Update:

It works. If you add --write 

npx destiny --write  "src/**/."

Not working:

npx destiny -W "src/**/." 

error: Path not found

**Comment by benawad** [comment]
I think it should be a lowercase `-w`, but either way, I'll update the readme

**Comment by AnatoleLucet** [comment]
You need tu use the `--write` flag. See `npx destiny --help`.

**Comment by danielpza** [comment]
We should improve the cli a bit, if the params are wrong or no input path are specified we should probably display the help message

**Comment by sQVe** [comment]
@danielpza That's close to how it works currently but with one exception. If you feed the `cli` with `--incorrect-option` it assumes that it is a path.

**Comment by danielpza** [comment]
Perhaps a `--incorrect-option is not a valid path` message.

**Comment by sQVe** [comment]
I think we should just keep it simple and ignore paths that start with `-` or `--` here: https://github.com/benawad/destiny/blob/develop/src/index.ts#L68

**Comment by danielpza** [comment]
Yeah, I don't see anyone naming their files `--my-file-goes-here.tsx`, but now I'm curious how others handle these cases :thinking:

**Comment by sQVe** [comment]
@danielpza They might, which is why I wrote it like this in the first place. I'm a bit unsure how to handle this in the best way.
