### ISSUE TITLE
Unexpected token { and no logging or other error output

### ISSUE THREAD

**Issue by seantcanavan** [benawad/destiny#85]
Hey destiny team,

I'm working with a webpack / babel project with Javascript and JSX mixed in and I'm getting this error when running the utility.

```
Fri Feb 28 12:03 PM code_base: npx destiny "src/**/*.*"
Unexpected token {
```

Unfortunately I have no idea how to proceed further without any additional output.

**Comment by AnatoleLucet** [comment]
Strange, can you please try to create a minimal reproduction in a repo and share us the link. Thanks you!

**Comment by seantcanavan** [comment]
@AnatoleLucet without any logging output I don't know which file(s) caused the error. And unfortunately I can't share company code directly. So if there's a way to find out the problem file I can start there and try to recreate the issue in another repo.

**Comment by AnatoleLucet** [comment]
Gosh, we need a debug feature. I'm struggling to reproduce it. 😕

**Comment by danielpza** [comment]
Just put a bunch of console.logs in several parts of destiny and see how it goes :smile:

**Comment by seantcanavan** [comment]
I'm still very much a front-end newbie but if it helps our project is using Flow `0.61.0`, node-sass `4.11.0` and probably some other funky stuff going on. I'm not sure how much non-standard JavaScript syntax is supported by the project since I know it re-writes imports and moves files so it might be struggling with flow type syntax? `import type { Action } from ../actions.js`. Maybe something like that?

**Comment by AnatoleLucet** [comment]
@seantcanavan I've just tried with `import type` and it does work.

**Comment by seantcanavan** [comment]
If you can try to get a build out with debugging for current file or file stack and current line it chokes on I can try to recreate it?

**Comment by benawad** [comment]
the simplest may be to clone the project, run `node lib/destiny.js path/to/src`, should give a stack trace

**Comment by seantcanavan** [comment]
```
/home/userwork/Downloads/destiny-0.4.0
Thu Mar 05 01:51 PM destiny-0.4.0: node lib/destiny.js /work/team/project/src/
INFO: Generating tree for: /work/team/project/src/
ERROR: Cannot find import ../_shared/actions/actions
If you think this is a bug, you can report it: https://github.com/benawad/destiny/issues
```

I added some `console.log` statements in `destiny.js` at line 424 ` if (pathWithExtension == null) {` in the `buildGraph` function.

```
parentFolder is /work/team/project/src
graph is { 'index.js': 
   [ '_shared/lib/segment/index.js',
     'app/components/index.jsx',
     'app/store/index.js' ],
  'app/index.js': [ 'app/components/appContainer.js', 'app/components/setup.jsx' ],
  'app/routes.js': 
   [ 'app/index.js',
     'feature5/containers/feature5.js',
     'feature5/components/feature5.jsx',
     'dashboard/index.js',
     'report/index.js',
     'feature1/index.js',
     'feature2/index.js',
     'dashboard/components/feature4/index.jsx',
     'dashboard/components/feature3/index.jsx',
     'dashboard/components/feature3/feature3.jsx',
     'dashboard/components/feature3/configuration/feature3Configuration.jsx',
     'dashboard/components/feature3/feature3NotificationSettings.jsx',
     'feature6/index.js',
     'app/actions.js' ],
  'app/actions.js': [ '_shared/actions/actionTypes.js' ] }
totalFiles is [ 'index.js', 'app/index.js', 'app/routes.js', 'app/actions.js' ]
filePath is /work/team/project/src/app/actions.js
start is app/actions.js
pathWithExtension is null
ERROR: Cannot find import ../_shared/actions/actions
```

actions.js contents:

```
/**
 * @flow
 *
 * Actions for app level tasks
 */

import { EventTypes } from 'redux-segment';
import {
  ACTION1,
  ACTION2,
  ACTION3,
  ACTION4,
  ACTION5,
  ACTION6,
  ACTION7,
  ACTION8,
  ACTION9,
  ACTION10,
  ACTION11,
  ACTION12
} from '../_shared/actions/actionTypes';
import type { Action } from '../_shared/actions/actions';

/**
 * function1 does stuff
 */
export function function1(argument1: Function): Action {
```


This is on Ubuntu 18.04 by the way working with our mono-repo from the root directory. I've shared as much as I think I can. If this isn't enough information I can try to dig out more information some time next week hopefully?

**Comment by moranje** [comment]
Is the last bracket supposed to be followed up by a closing bracket?

**Comment by seantcanavan** [comment]
@moranje no idea - the error didn't say. It didn't mention a line or symbol number so not sure if it failed to find a closing `}`. If it did it's most likely in the wrong as the code does compile - promise :smile:

**Comment by AnatoleLucet** [comment]
Hey @seantcanavan, we've just shipped a `--debug` flag in Destiny `0.5.0`.
Can you try to run `npx destiny "src/**/*.*" --debug`?

**Comment by seantcanavan** [comment]
Here's the end of the output:

```
INFO: Generating tree for: src/**/*.*
ERROR: Cannot find import ../_shared/actions/actions
If you think this is a bug, you can report it: https://github.com/benawad/destiny/issues
DEBUG: +438ms exiting
```

If you want me to paste the rest of it I'm going to have to write a python script to anonymize the filenames or something similar.

**Comment by benawad** [comment]
@seantcanavan I'm assuming the path `../_shared/actions/actions` from that file exists, would the path with the file extension be `../_shared/actions/actions.js`?

**Comment by seantcanavan** [comment]
I think I know what might be causing this:

Dozens of files reference our generic `Action` type via an import line like this:

`import type { Action } from '../_shared/actions/actions';`

the file itself is:
/repo/team/project/src/_shared/actions/actions.js.flow

The first 10 lines of the file are:

```
// @flow

export type Action = {
  type: string;
  payload?: *;
  meta?: {
    data?: *;
    analytics?: Object;
  };
}
...
...
```

**Comment by benawad** [comment]
yep that's it we don't resolve the `.js.flow` file type, I'll add this.
