### ISSUE TITLE
Destiny only treat import paths that start with a dot

### ISSUE THREAD

**Issue by AnatoleLucet** [benawad/destiny#87]
[Our regex](https://github.com/benawad/destiny/blob/001ea49279314b7d41ff4e189eff1c00e4062d87/src/index/shared/findImports.ts#L5) only match with import paths that start with a dot.

That's an issue because destiny is trying to resolve this import's package name as a path:
```js
import '..something';
// or
import '.something';
```

Also I don't think npm is allowing dots in packages name. But destiny should probably ignore this kind of import anyway...

See:
https://regexr.com/4vc8q

**Comment by sQVe** [comment]
That should be solved easily. A tougher problem are cases where the project uses specific paths to resolve internal parths like `/src` och `@app`. This is getting more and more common in large codebases.
